---
version: 2
plan:
  project-key: ITOPS
  key: STATD
  name: STATD-PROD

stages:
  - Docker:
    - containerize
  - Build:
    - build

containerize:
  tasks:
    - script:
      - docker build -t docker.io/shyamin/hello:latest .
      - docker login --username shyamin --password "${bamboo.docker_token}" docker.io
      - docker push docker.io/shyamin/hello:latest

build:
  tasks:
    - script:
      - make dist
  docker:
    image: shyamin/hello:latest
