---
version: 2
plan:
  project-key: ITOPS
  key: STATD
  name: STATD-PROD

stages:
  - Docker:
    - docker_create
  - Build:
    - build

docker_create:
  tasks:
    - script:
      - docker build -t docker.io/shyamin/hello:latest .
#       - echo "${bamboo.docker}"
      - docker login --username shyamin --password "${bamboo.docker_token}" docker.io

build:
  tasks:
    - script:
      - make dist
  docker:
    image: golang:alpine
