---
version: 2
plan:
  project-key: ITOPS
  key: STATD
  name: STATD-PROD

stages:
  - Docker:
    - docker_create
  - Build:
    - build

docker_create:
  tasks:
    - script:
      - docker build -t docker.io/shyamin/hello-docker:latest .

build:
  tasks:
    - script:
      - make dist
  docker:
    image: golang:alpine
